[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spineclf"
version = "0.1.0"
description = "Spine classification project - MAIA"
authors = [{name = "MAIA Team"}]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]